import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//     // By default, Docusaurus generates a sidebar from the docs folder structure
//     tutorialSidebar: [{
//         type: 'autogenerated', dirName: '.'
//     }],

//     // But you can create a sidebar manually
//     /*
//     tutorialSidebar: [
//       'intro',
//       'hello',
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//      */
// };

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'datalogger/introduction',
        'datalogger/hardware_overview',
        'datalogger/hardware_hookup',
        'datalogger/system-operation',
        {
            type: 'category',
            label: 'Settings',
            link: {
                type: 'generated-index'
            },
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'General',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/general/gen-app-set',
                        'datalogger/settings/general/gen-time-setup',
                        'datalogger/settings/general/gen-save-settings'
                    ]
                },
                {
                    type: 'category',
                    label: 'Network',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/network/net-wifi-setup',
                        'datalogger/settings/network/net-ntp-setup'
                    ]
                },
                {
                    type: 'category',
                    label: 'Logging',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/logging/log-settings-logger',
                        'datalogger/settings/logging/log-settings-timer',
                        'datalogger/settings/logging/log-settings-file',
                        'datalogger/settings/logging/log-settings-interrupt',
                    ]
                },
                {
                    type: 'category',
                    label: 'GPIO Devices',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/gpio-devices/gpio-extern-serial',
                        'datalogger/settings/gpio-devices/gpio-soil-moisture',
                        'datalogger/settings/gpio-devices/gpio-analog-pin-sensor'
                    ]
                },
                {
                    type: 'category',
                    label: 'Services',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        {
                            type: 'category',
                            label: 'IoT Services',
                            link: {
                                type: 'generated-index'
                            },
                            collapsed: false,
                            items: [
                                'datalogger/settings/services/iot-services/iot_mqtt',
                                'datalogger/settings/services/iot-services/iot_aws',
                                'datalogger/settings/services/iot-services/iot_thingspeak',
                                'datalogger/settings/services/iot-services/iot_azure',
                                'datalogger/settings/services/iot-services/iot_http',
                                'datalogger/settings/services/iot-services/iot_arduino_iot_cloud'
                            ]
                        },
                        "datalogger/settings/services/iot_web_server"
                    ]
                },
                {
                    type: 'category',
                    label: 'Advanced',
                    link: {
                        type: 'generated-index'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/advanced/adv-system-update'
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Device Settings',
            link: {
                type: 'generated-index'
            },
            collapsed: false,
            items: [
                'datalogger/device-settings/gnss-pps-log'
            ]
        },
        {
            type: 'category',
            label: 'Resources',
            link: {
                type: 'generated-index'
            },
            collapsed: false,
            items: [
                'datalogger/resources/supported_devices',
                'datalogger/resources/ref-serial-terms'
            ]
        }
    ]
};

export default sidebars;
