import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//     // By default, Docusaurus generates a sidebar from the docs folder structure
//     tutorialSidebar: [{
//         type: 'autogenerated', dirName: '.'
//     }],

//     // But you can create a sidebar manually
//     /*
//     tutorialSidebar: [
//       'intro',
//       'hello',
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//      */
// };

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'datalogger/introduction',
        'datalogger/hardware_overview',
        'datalogger/hardware_hookup',
        {
            type: 'category',
            label: 'Settings',
            link: {
                type: 'doc',
                id: 'datalogger/settings/general/gen-app-set'
            },
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'General',
                    link:{
                        type:'doc',
                        id: 'datalogger/settings/general/gen-app-set'
                    },
                    collapsed: false,
                    items: [
                        'datalogger/settings/general/gen-app-set',
                        'datalogger/settings/general/gen-time-setup',
                        'datalogger/settings/general/gen-save-settings'
                    ]
                }
            ]
        },
        {
            type: 'category',
            label: 'Resources',
            link: {
                type: 'doc',
                id: 'datalogger/resources/supported_devices'
            },
            collapsed: false,
            items: [
                'datalogger/resources/supported_devices',
                'datalogger/resources/ref-serial-terms'
            ]
        }
    ]
};

export default sidebars;
